### ISSUE TITLE
quote: Properly handle colons

### ISSUE THREAD

**Issue by kernelpanic3** [staticfox/rps#3]
[23:15:58] <VASirens> !q add [23:15:28] <BlindSight> boy more bugs
[23:16:06] <Bot> ID: #3 - Submitted By: VASirens - 11/28/15 @ 11:16 PM Eastern - [23

**Comment by staticfox** [comment]
Ohhhh this might be a problem with the core of how it hashes irc strings

**Comment by MrHamel** [comment]
I doubt it. Do a `puts` on message event before it gets processed.

**Comment by staticfox** [comment]
I've noticed though that other modules are receiving truncated messages as well due to colon splitting

**Comment by MrHamel** [comment]
Yah, on PRIVMSG, it needs to be split up using a regex. It's how the tf2bot does it.

**Comment by MrHamel** [comment]
`:(.*)!(.*)@(.*) PRIVMSG (.*) :(.*)` - it worked with ":nick!user@ip-address PRIVMSG your-nick :VERSION"

**Comment by staticfox** [comment]
https://github.com/staticfox/rps/blob/master/app/events/ircmsg.rb#L38-L42

Doesn't seem right to me?

**Comment by MrHamel** [comment]
Yah that was done very horribly.

**Comment by MrHamel** [comment]
if I wanted to get fancy with the regex, I could have it take into account the nick and channel max lengths provided by the IRCd.

**Comment by staticfox** [comment]
Yeah but that information is not sent during netburst

**Comment by staticfox** [comment]
fixed in https://github.com/staticfox/rps/compare/4c642a76e1e6...5a7e4e23b9a6 re-open if it still continues to be an issue
